name: Build and Upload JAR

on:
  workflow_dispatch:
    inputs:
      enviroment:
        description: 'Compile'
        required: false
        default: 'Staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y Maven

      - name: Build with Maven
        run: mvn -f ./maven/pom.xml clean package

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: Xaero_FPE
          path: /home/runner/work/Xaero_Fair-Play_Enforcer/.../*.jar # Need to replace with end folder once completed.
